# Generated by Django 5.0.3 on 2024-03-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='issues',
        ),
        migrations.AddField(
            model_name='desktop',
            name='room',
            field=models.CharField(default='Storage Room', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='room',
            field=models.CharField(default='Storage Room', max_length=50),
        ),
        migrations.AddField(
            model_name='mobile',
            name='room',
            field=models.CharField(default='Storage Room', max_length=50),
        ),
    ]
